from PyQt5 import QtCore, QtGui, QtWidgets
from db_operations import DB


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(791, 635)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.loginRegisterFrame = QtWidgets.QFrame(self.centralwidget)
        self.loginRegisterFrame.setEnabled(True)
        self.loginRegisterFrame.setGeometry(QtCore.QRect(250, 100, 311, 341))
        self.loginRegisterFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.loginRegisterFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.loginRegisterFrame.setObjectName("loginRegisterFrame")
        self.emailLineEdit = QtWidgets.QLineEdit(self.loginRegisterFrame)
        self.emailLineEdit.setGeometry(QtCore.QRect(80, 100, 111, 20))
        self.emailLineEdit.setObjectName("emailLineEdit")
        self.passwordLineEdit = QtWidgets.QLineEdit(self.loginRegisterFrame)
        self.passwordLineEdit.setGeometry(QtCore.QRect(80, 130, 111, 20))
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.emailLabel = QtWidgets.QLabel(self.loginRegisterFrame)
        self.emailLabel.setGeometry(QtCore.QRect(30, 100, 47, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setBold(True)
        font.setWeight(75)
        self.emailLabel.setFont(font)
        self.emailLabel.setObjectName("emailLabel")
        self.passwordLabel = QtWidgets.QLabel(self.loginRegisterFrame)
        self.passwordLabel.setGeometry(QtCore.QRect(10, 130, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setBold(True)
        font.setWeight(75)
        self.passwordLabel.setFont(font)
        self.passwordLabel.setObjectName("passwordLabel")
        self.welcomeLabel = QtWidgets.QLabel(self.loginRegisterFrame)
        self.welcomeLabel.setGeometry(QtCore.QRect(80, 20, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.welcomeLabel.setFont(font)
        self.welcomeLabel.setObjectName("welcomeLabel")
        self.loginButton = QtWidgets.QPushButton(self.loginRegisterFrame)
        self.loginButton.setGeometry(QtCore.QRect(80, 160, 111, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 212, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(56, 113, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 212, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 212, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(56, 113, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 212, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 212, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(56, 113, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.loginButton.setPalette(palette)
        self.loginButton.setFlat(False)
        self.loginButton.setObjectName("loginButton")
        self.signUpButton = QtWidgets.QPushButton(self.loginRegisterFrame)
        self.signUpButton.setGeometry(QtCore.QRect(80, 240, 111, 23))
        self.signUpButton.setObjectName("signUpButton")
        self.signUpNowLabel = QtWidgets.QLabel(self.loginRegisterFrame)
        self.signUpNowLabel.setGeometry(QtCore.QRect(80, 200, 161, 41))
        self.signUpNowLabel.setObjectName("signUpNowLabel")
        self.incorretCredentialsLabel = QtWidgets.QLabel(self.loginRegisterFrame)
        self.incorretCredentialsLabel.setGeometry(QtCore.QRect(80, 80, 121, 16))
        self.incorretCredentialsLabel.setObjectName("incorretCredentialsLabel")
        self.helpButton = QtWidgets.QPushButton(self.loginRegisterFrame)
        self.helpButton.setGeometry(QtCore.QRect(230, 310, 75, 23))
        self.helpButton.setObjectName("helpButton")
        self.helpLabel = QtWidgets.QLabel(self.loginRegisterFrame)
        self.helpLabel.setGeometry(QtCore.QRect(230, 260, 81, 41))
        self.helpLabel.setObjectName("helpLabel")
        self.helpFrame = QtWidgets.QFrame(self.centralwidget)
        self.helpFrame.setEnabled(True)
        self.helpFrame.setGeometry(QtCore.QRect(250, 100, 311, 331))
        self.helpFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.helpFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.helpFrame.setObjectName("helpFrame")
        self.changeemailButton = QtWidgets.QPushButton(self.helpFrame)
        self.changeemailButton.setGeometry(QtCore.QRect(0, 100, 121, 41))
        self.changeemailButton.setObjectName("changeemailButton")
        self.changepasswordButton = QtWidgets.QPushButton(self.helpFrame)
        self.changepasswordButton.setGeometry(QtCore.QRect(0, 160, 141, 41))
        self.changepasswordButton.setObjectName("changepasswordButton")
        self.goBackButton_HelpFrame = QtWidgets.QPushButton(self.helpFrame)
        self.goBackButton_HelpFrame.setGeometry(QtCore.QRect(0, 10, 75, 23))
        self.goBackButton_HelpFrame.setObjectName("goBackButton_HelpFrame")
        self.emailHelpFrame = QtWidgets.QFrame(self.centralwidget)
        self.emailHelpFrame.setEnabled(True)
        self.emailHelpFrame.setGeometry(QtCore.QRect(250, 100, 311, 331))
        self.emailHelpFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.emailHelpFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.emailHelpFrame.setObjectName("emailHelpFrame")
        self.insertEmailLabel = QtWidgets.QLabel(self.emailHelpFrame)
        self.insertEmailLabel.setGeometry(QtCore.QRect(10, 20, 281, 91))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(16)
        self.insertEmailLabel.setFont(font)
        self.insertEmailLabel.setObjectName("insertEmailLabel")
        self.accountEmailLineEdit = QtWidgets.QLineEdit(self.emailHelpFrame)
        self.accountEmailLineEdit.setGeometry(QtCore.QRect(70, 160, 131, 20))
        self.accountEmailLineEdit.setObjectName("accountEmailLineEdit")
        self.yourEmailLabel = QtWidgets.QLabel(self.emailHelpFrame)
        self.yourEmailLabel.setGeometry(QtCore.QRect(10, 160, 71, 21))
        self.yourEmailLabel.setObjectName("yourEmailLabel")
        self.sendCodeButton = QtWidgets.QPushButton(self.emailHelpFrame)
        self.sendCodeButton.setGeometry(QtCore.QRect(200, 150, 91, 41))
        self.sendCodeButton.setObjectName("sendCodeButton")
        self.invalidAccountEmail = QtWidgets.QLabel(self.emailHelpFrame)
        self.invalidAccountEmail.setGeometry(QtCore.QRect(100, 140, 81, 16))
        self.invalidAccountEmail.setObjectName("invalidAccountEmail")
        self.goBackButton = QtWidgets.QPushButton(self.emailHelpFrame)
        self.goBackButton.setGeometry(QtCore.QRect(0, 10, 75, 23))
        self.goBackButton.setObjectName("goBackButton")
        self.finalEmailAccountHelpFrame = QtWidgets.QFrame(self.centralwidget)
        self.finalEmailAccountHelpFrame.setEnabled(True)
        self.finalEmailAccountHelpFrame.setGeometry(QtCore.QRect(250, 99, 311, 331))
        self.finalEmailAccountHelpFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.finalEmailAccountHelpFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.finalEmailAccountHelpFrame.setObjectName("finalEmailAccountHelpFrame")
        self.insertEmailVerificationCode = QtWidgets.QLabel(self.finalEmailAccountHelpFrame)
        self.insertEmailVerificationCode.setGeometry(QtCore.QRect(30, 10, 271, 101))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(16)
        self.insertEmailVerificationCode.setFont(font)
        self.insertEmailVerificationCode.setObjectName("insertEmailVerificationCode")
        self.emailVerificationCodeLineEdit = QtWidgets.QLineEdit(self.finalEmailAccountHelpFrame)
        self.emailVerificationCodeLineEdit.setGeometry(QtCore.QRect(100, 140, 113, 20))
        self.emailVerificationCodeLineEdit.setObjectName("emailVerificationCodeLineEdit")
        self.verificationCodeLabel = QtWidgets.QLabel(self.finalEmailAccountHelpFrame)
        self.verificationCodeLabel.setGeometry(QtCore.QRect(10, 120, 111, 61))
        self.verificationCodeLabel.setObjectName("verificationCodeLabel")
        self.verifyEmailCodeButton = QtWidgets.QPushButton(self.finalEmailAccountHelpFrame)
        self.verifyEmailCodeButton.setGeometry(QtCore.QRect(220, 140, 75, 23))
        self.verifyEmailCodeButton.setObjectName("verifyEmailCodeButton")
        self.invalidEmailVerificationCode = QtWidgets.QLabel(self.finalEmailAccountHelpFrame)
        self.invalidEmailVerificationCode.setGeometry(QtCore.QRect(100, 90, 121, 81))
        self.invalidEmailVerificationCode.setObjectName("invalidEmailVerificationCode")
        self.resendEmailVerificationCode = QtWidgets.QPushButton(self.finalEmailAccountHelpFrame)
        self.resendEmailVerificationCode.setGeometry(QtCore.QRect(90, 210, 131, 41))
        self.resendEmailVerificationCode.setObjectName("resendEmailVerificationCode")
        self.label = QtWidgets.QLabel(self.finalEmailAccountHelpFrame)
        self.label.setGeometry(QtCore.QRect(70, 170, 191, 20))
        self.label.setObjectName("label")
        self.changeEmailAccountFrame = QtWidgets.QFrame(self.centralwidget)
        self.changeEmailAccountFrame.setEnabled(True)
        self.changeEmailAccountFrame.setGeometry(QtCore.QRect(250, 99, 311, 331))
        self.changeEmailAccountFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.changeEmailAccountFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.changeEmailAccountFrame.setObjectName("changeEmailAccountFrame")
        self.newAccountEmailLabel = QtWidgets.QLabel(self.changeEmailAccountFrame)
        self.newAccountEmailLabel.setGeometry(QtCore.QRect(60, 70, 101, 41))
        self.newAccountEmailLabel.setObjectName("newAccountEmailLabel")
        self.newAccountEmailLineEdit = QtWidgets.QLineEdit(self.changeEmailAccountFrame)
        self.newAccountEmailLineEdit.setGeometry(QtCore.QRect(120, 80, 113, 20))
        self.newAccountEmailLineEdit.setObjectName("newAccountEmailLineEdit")
        self.confirmNewAccountEmailLineEdit = QtWidgets.QLineEdit(self.changeEmailAccountFrame)
        self.confirmNewAccountEmailLineEdit.setGeometry(QtCore.QRect(120, 110, 113, 20))
        self.confirmNewAccountEmailLineEdit.setObjectName("confirmNewAccountEmailLineEdit")
        self.confirmNewAccountEmailLabel = QtWidgets.QLabel(self.changeEmailAccountFrame)
        self.confirmNewAccountEmailLabel.setGeometry(QtCore.QRect(20, 110, 101, 16))
        self.confirmNewAccountEmailLabel.setObjectName("confirmNewAccountEmailLabel")
        self.insertNewAccountEmailAdressLabel = QtWidgets.QLabel(self.changeEmailAccountFrame)
        self.insertNewAccountEmailAdressLabel.setGeometry(QtCore.QRect(50, -30, 251, 141))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(16)
        self.insertNewAccountEmailAdressLabel.setFont(font)
        self.insertNewAccountEmailAdressLabel.setObjectName("insertNewAccountEmailAdressLabel")
        self.saveNewEmailAdressButton = QtWidgets.QPushButton(self.changeEmailAccountFrame)
        self.saveNewEmailAdressButton.setGeometry(QtCore.QRect(120, 140, 111, 41))
        self.saveNewEmailAdressButton.setObjectName("saveNewEmailAdressButton")
        self.createAccountFrame = QtWidgets.QFrame(self.centralwidget)
        self.createAccountFrame.setEnabled(True)
        self.createAccountFrame.setGeometry(QtCore.QRect(250, 100, 311, 341))
        self.createAccountFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.createAccountFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.createAccountFrame.setObjectName("createAccountFrame")
        self.createAccountLabel = QtWidgets.QLabel(self.createAccountFrame)
        self.createAccountLabel.setGeometry(QtCore.QRect(70, 0, 191, 71))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(16)
        self.createAccountLabel.setFont(font)
        self.createAccountLabel.setObjectName("createAccountLabel")
        self.createEmailLabel = QtWidgets.QLabel(self.createAccountFrame)
        self.createEmailLabel.setGeometry(QtCore.QRect(70, 100, 31, 16))
        self.createEmailLabel.setObjectName("createEmailLabel")
        self.createPasswordLabel = QtWidgets.QLabel(self.createAccountFrame)
        self.createPasswordLabel.setGeometry(QtCore.QRect(50, 130, 51, 16))
        self.createPasswordLabel.setObjectName("createPasswordLabel")
        self.confirmPasswordLabel = QtWidgets.QLabel(self.createAccountFrame)
        self.confirmPasswordLabel.setGeometry(QtCore.QRect(10, 160, 91, 16))
        self.confirmPasswordLabel.setObjectName("confirmPasswordLabel")
        self.createEmailLineEdit = QtWidgets.QLineEdit(self.createAccountFrame)
        self.createEmailLineEdit.setGeometry(QtCore.QRect(100, 100, 113, 20))
        self.createEmailLineEdit.setObjectName("createEmailLineEdit")
        self.createPasswordLineEdit = QtWidgets.QLineEdit(self.createAccountFrame)
        self.createPasswordLineEdit.setGeometry(QtCore.QRect(100, 130, 113, 20))
        self.createPasswordLineEdit.setInputMethodHints(QtCore.Qt.ImhHiddenText | QtCore.Qt.ImhSensitiveData)
        self.createPasswordLineEdit.setObjectName("createPasswordLineEdit")
        self.confimPasswordLineEdit = QtWidgets.QLineEdit(self.createAccountFrame)
        self.confimPasswordLineEdit.setGeometry(QtCore.QRect(100, 160, 113, 20))
        self.confimPasswordLineEdit.setObjectName("confimPasswordLineEdit")
        self.createAccountButton = QtWidgets.QPushButton(self.createAccountFrame)
        self.createAccountButton.setGeometry(QtCore.QRect(100, 190, 111, 51))
        self.createAccountButton.setObjectName("createAccountButton")
        self.passwordsDontMatchLabel = QtWidgets.QLabel(self.createAccountFrame)
        self.passwordsDontMatchLabel.setGeometry(QtCore.QRect(100, 60, 191, 41))
        self.passwordsDontMatchLabel.setObjectName("passwordsDontMatchLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 791, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # FRAME VISIBILITIES
        self.loginRegisterFrame.setVisible(True)
        self.createAccountFrame.setVisible(False)
        self.changeEmailAccountFrame.setVisible(False)
        self.finalEmailAccountHelpFrame.setVisible(False)
        self.helpFrame.setVisible(False)
        self.emailHelpFrame.setVisible(False)

        # WIDGETS VISIBILITIES
        self.incorretCredentialsLabel.setVisible(False)
        self.passwordsDontMatchLabel.setVisible(False)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.emailLabel.setText(_translate("MainWindow", "EMAIL :"))
        self.passwordLabel.setText(_translate("MainWindow", "PASSWORD:"))
        self.welcomeLabel.setText(_translate("MainWindow", "Welcome to \n"
                                                           "Lummix !"))
        self.loginButton.setText(_translate("MainWindow", "Login"))
        self.signUpButton.setText(_translate("MainWindow", "Sign Up"))
        self.signUpNowLabel.setText(_translate("MainWindow", "Don\'t have a Lummix account? \n"
                                                             " Sign Up now !"))
        self.incorretCredentialsLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" "
                                                                       "color:#ff0000;\">Invalid Email or Password"
                                                                       "</span></p></body></html>"))
        self.helpButton.setText(_translate("MainWindow", "Help Me"))
        self.helpLabel.setText(_translate("MainWindow", "Need Help? \n"
                                                        "Click on the \n"
                                                        "button below"))
        self.changeemailButton.setText(_translate("MainWindow", "Change Account Email"))
        self.changepasswordButton.setText(_translate("MainWindow", "Change Account Password"))
        self.goBackButton_HelpFrame.setText(_translate("MainWindow", "Go Back"))
        self.insertEmailLabel.setText(_translate("MainWindow", "\n"
                                                               "Insert your account email\n"
                                                               "so we can send you\n"
                                                               " the verification code"))
        self.yourEmailLabel.setText(_translate("MainWindow", "Your Email: "))
        self.sendCodeButton.setText(_translate("MainWindow", "Send \n"
                                                             "Verification Code"))
        self.invalidAccountEmail.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;"
                                                                  "\">Invalid Email</span></p></body></html>"))
        self.goBackButton.setText(_translate("MainWindow", "Go Back"))
        self.insertEmailVerificationCode.setText(_translate("MainWindow", "Insert the verification \n"
                                                                          "code that we \n"
                                                                          "sent to you"))
        self.verificationCodeLabel.setText(_translate("MainWindow", "Verification Code:"))
        self.verifyEmailCodeButton.setText(_translate("MainWindow", "Verify"))
        self.invalidEmailVerificationCode.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" "
                                                                           "color:#ff0000;\">Invalid Verification "
                                                                           "Code</span></p></body></html>"))
        self.resendEmailVerificationCode.setText(_translate("MainWindow", "Resend Verification Code"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#006818;\">A new "
                                                    "verification code has been sent</span></p></body></html>"))
        self.newAccountEmailLabel.setText(_translate("MainWindow", "New Email: "))
        self.confirmNewAccountEmailLabel.setText(_translate("MainWindow", "Confirm New Email:"))
        self.insertNewAccountEmailAdressLabel.setText(_translate("MainWindow", "Insert the new \n"
                                                                               "account email address"))
        self.saveNewEmailAdressButton.setText(_translate("MainWindow", "Save Changes"))
        self.createAccountLabel.setText(_translate("MainWindow", "Create a \n"
                                                                 "Lummix Account"))
        self.createEmailLabel.setText(_translate("MainWindow", "Email:"))
        self.createPasswordLabel.setText(_translate("MainWindow", "Password:"))
        self.confirmPasswordLabel.setText(_translate("MainWindow", "Confirm Password:"))
        self.createAccountButton.setText(_translate("MainWindow", "Create \n"
                                                                  "Account"))
        self.passwordsDontMatchLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" "
                                                                      "color:#ff0000;\">Passwords Don\'t Match</span>"
                                                                      "</p></body></html>"))

        # BUTTON ACTIONS
        self.loginButton.clicked.connect(lambda: self.login())
        self.signUpButton.clicked.connect(lambda: self.signUpAccount_clicked())
        self.createAccountButton.clicked.connect(lambda: self.createAccount())

    def login(self):
        User = DB('database.db')
        try:
            email = self.emailLineEdit.text()
            password = self.passwordLineEdit.text()

            User.login_account(email, password)

            result = User.cursor.fetchone()

            if result is not None:
                self.loginRegisterFrame.setVisible(False)
                self.incorretCredentialsLabel.setVisible(False)

            else:
                self.incorretCredentialsLabel.setVisible(True)

        except User.conn.Error as e:
            print('Error')

    def signUpAccount_clicked(self):
        self.loginRegisterFrame.setVisible(False)
        self.incorretCredentialsLabel.setVisible(False)
        self.createAccountFrame.setVisible(True)

    def createAccount(self):
        newUser = DB('database.db')

        userEmail = self.createEmailLineEdit.text()
        userPassword = self.createPasswordLineEdit.text()
        confirmUserPassword = self.confimPasswordLineEdit.text()

        if userPassword == confirmUserPassword:
            self.passwordsDontMatchLabel.setVisible(False)
            newUser.create_account(email_address=userEmail, password=userPassword)

        else:
            self.passwordsDontMatchLabel.setVisible(True)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
